### ISSUE TITLE
feat: Add support SAT file version 2.6

### ISSUE THREAD

**Issue by Masber** [eth-cscs/manta#14]
Add support for the following structs in SAT files:

configurations (cray-product-catalog in https://github.com/Cray-HPE/cray-product-catalog):

https://cray-hpe.github.io/docs-sat/en-26/usage/sat_bootprep/#define-cfs-configurations

```
        product:
          name: cos
          version: 2.4.122
          branch: cscs-23.06.0
```

images:

see https://cray-hpe.github.io/docs-sat/en-26/usage/sat_bootprep/#define-ims-images

```
  base:
    image_ref: base_cos_image
```
and
```
  base:
    product:
      name: cos
      type: recipe
      version: "2.4.139"
```
also support old SAT file version
```
- name: image-cos-__DATE__
  ims:
    is_recipe: false
    id: 22294fa6-f869-4acf-bcf4-0d27df5e824b
  configuration: cos-config-__DATE__
  configuration_group_names:
  - Compute
```
