### ISSUE TITLE
Error in converting CFS configuration layer commit id field form yaml SAT file 

### ISSUE THREAD

**Issue by Masber** [eth-cscs/manta#29]
Manta fails in creating CFS configuration layer from SAT file when deserializing commit id value.

From:

```
  - name: psi
    playbook: layer0.yml
    git:
      url: https://api-gw-service-nmn.local/vcs/cray/vcluster-psidev-ansible.git
      commit: b81d7873da105c1775865588f4b8ab77842de60d
```

To:

```
| fora-cos-config-manuel-test-5    | 2024-02-15T19:46:29Z | COMMIT: ec773be15f72aed7c4a2161540200dec14d907f3 NAME: ss11               |
|                                  |                      | COMMIT: 06dcdc36181a05552ceae98da67bb16604dee34a NAME: cos                |
|                                  |                      | COMMIT: 64ab09c1adb0a431c479f8521c528dc9c116a869 NAME: csm                |
|                                  |                      | COMMIT: 3a0d13133a66a9ea4a6763a9202264a2250a113c NAME: cscs               |
|                                  |                      | COMMIT: Not defined NAME: psi                                             |
```
