### ISSUE TITLE
FEATURE: add values to expand SAT template file through CLI params

### ISSUE THREAD

**Issue by Masber** [eth-cscs/manta#38]
A new feature was recently added to manta to template SAT file with values defined in a session var file.
An upgrade to this would be to give the option to overwrite the values files by passing the vars values through the cli

example:
`manta apply cluster -f my_sat_file_template.yaml -V my_values.yaml --var "config.name="`

The command above would overwrite the `version` value in `my_values.yaml` to `v1.0.3`. Then expand the `my_sat_file_template.yaml`

Having:

```
# cat my_values.yaml
---
hsm:
  group_name: "zinal_cta"
config:
  name: "test-config"
  version: "v1.0.2"
image:
  version: "v1.0.6"
bos_st:
  name: "deploy-cluster-action"
  version: "v1.0"
```

And var `config.name=new-value`

The values in `my_values.yaml` should update to:

```
hsm:
  group_name: zinal_cta
config:
  name: new-value
  version: v1.0.0
image:
  version: v1.0.5
bos_st:
  name: deploy-cluster-action
  version: v1.0
```
