### ISSUE TITLE
BUG: manta ignoring old version of session_template section in SAT file

### ISSUE THREAD

**Issue by Masber** [eth-cscs/manta#57]
New SAT file schema don't follow the session_template like below anymore:

```
session_templates:
- name: zinal-client-{{ version }}
  image: zinal-image-20231204014122
  configuration: zinal-client-{{ version }}
  bos_parameters:
    boot_sets:
      compute:
        kernel_parameters: ip=dhcp quiet spire_join_token=${SPIRE_JOIN_TOKEN}
        node_groups:
        - zinal_tds
```

Because manta tries to be backward compatible, we will add support to this
